#!/usr/bin/env python3
"""Freeze GDT291 before context decomposition scoring."""
from __future__ import annotations
import csv,hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent;METHOD=R/'GDT291_HOST_POSITION_CONTEXT_DECOMPOSITION_METHOD.md';DESIGN=R/'gdt291_design.json';MAN=R/'gdt291_freeze_manifest.tsv';PANELS=['AUGSBURG_ACCOUNTS_1402_1424','ARBITRARY_LOCAL_CODEBOOK','COMPOSITIONAL_TECHNICAL_NOTATION','HYBRID_SHORTHAND','LATIN_SCHOLASTIC_GRAPHEMATIC','LATIN_MEDICAL_GRAPHEMATIC','LATIN_15C_GRAPHEMATIC','VOYNICH_REFERENCE'];ART=['gdt290_result.json','gdt290_validation.json','gdt289_result.json','gdt286_result.json','gdt278_native_event_inventory.tsv','gdt288_result.json']
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def csha(v):return hashlib.sha256(json.dumps(v,sort_keys=True,ensure_ascii=True,separators=(',',':')).encode()).hexdigest()
def main():
 with MAN.open('w',encoding='utf8',newline='') as h:w=csv.DictWriter(h,['artifact','frozen_sha256'],delimiter='\t',lineterminator='\n');w.writeheader();w.writerows([{'artifact':x,'frozen_sha256':sha(R/x)} for x in ART])
 d={'schema':'GDT291_HOST_POSITION_CONTEXT_DECOMPOSITION_DESIGN_V1','status':'FROZEN_BEFORE_GDT291_SCORING','panels':PANELS,'events_per_panel':8448,'outcome':'FROZEN_WRAPPER_CLASS','models':['SHAPE_CONTEXT','RECORD_CONTEXT','NONWRAPPER_COMPILER','EXACT_HOST_RICH','EXACT_HOST_X_POSITION_RICH','EXACT_HOST_SHAPE','EXACT_HOST_X_POSITION_SHAPE'],'shape_context':['section','currier','hand','register','within_field_position','host_length','first_host_character','last_host_character'],'record_context':['record_ordinal_bucket_1_2_3to4_5plus','field_ordinal_bucket_1_2_3to4_5plus','physical_line_group_position','line_close','paragraph_close','known_label_renderer'],'nonwrapper_compiler':['local_frame','inner_d','right_family','dy_closure','b3'],'forbidden_predictors':['wrapper','q_flag','target_page_wrapper_history'],'global_prior':'DIRICHLET_ONE_HALF','primary_prior_mass':11.0,'voynich_prior_sensitivities':[5.0,22.0],'primary_split':'HELD_PHYSICAL_FOLIO','voynich_transfer_sensitivities':['HELD_SECTION','HELD_HAND'],'decision':{'reversed':'HOST_POSITION_EFFECT_REVERSED_BY_RICH_CONTEXT','reduced':'HOST_POSITION_EFFECT_REDUCED_BUT_REMAINS','persists':'HOST_POSITION_EFFECT_PERSISTS_OR_STRENGTHENS_RICH_CONTEXT','no_anchor':'NO_POSITIVE_TARGET_HISTORY_FREE_HOST_POSITION_ANCHOR'},'new_corpora':0,'new_architectures':0,'semantic_assignments':0,'page_host_substrings_mined':0,'claim_ceiling':'Nested formal wrapper-context decomposition only; no lexical class morphology function abbreviation sound language meaning plaintext or translation.','f84':{'input_files':0,'opened':False,'parsed':False,'retained':False,'joined':False,'scored':False},'freeze_manifest_sha256':sha(MAN),'method_sha256':sha(METHOD),'implementation':{'freeze_gdt291_host_position_context_decomposition.py':sha(Path(__file__))}};d['content_sha256']=csha(d);DESIGN.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':d['status'],'content_sha256':d['content_sha256']},sort_keys=True))
if __name__=='__main__':main()
