#!/usr/bin/env python3
"""Freeze GDT134 before enumerating the expanded external line-pair panel."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parent;OUT=ROOT/'gdt134_prediction.json'
FILES=('GDT134_GENERAL_ADJACENT_CONTINUATION_TRANSFER_METHOD.md','gdt132_result.json','gdt133_result.json','gdt016_group_state_inventory.tsv','gdt046_line_frames.tsv','gdt127_q20_field_inventory.tsv','q20ob001_source_panel.tsv','run_gdt131_q20_cross_line_field_onset.py','run_gdt132_cross_register_continuation_arity.py')
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def csha(v):return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest()
x={'schema':'GDT134_GENERAL_ADJACENT_CONTINUATION_TRANSFER_PREDICTION_V1','status':'FROZEN_BEFORE_GENERAL_ADJACENT_PAIR_ENUMERATION','training':'GDT132_Q20_ZL3b_170_RECORDS','external_selection':'ALL_COMPLETE_NUMERIC_ADJACENT_PAIRS_WITH_NEXT_PARAGRAPH_START_0_IN_H_B_P_T_C_EXCLUDE_Q20_FOLIOS','models':['RAW_CHAR3','HOST_CHAR3','COMPILER12'],'target':'NEXT_LINE_FIRST_FIELD_GROUP_COUNT_BIN_1_2_3_4PLUS','primary_subset':'FIRST_LINE_PARAGRAPH_START_0','exact_null':'SECTION_CURRIER_HAND_FIRST_START_SOURCE_COUNT_FINAL_FIELD_GROUPS_HOST_LENGTH_RAW_LENGTH','worlds':4096,'capacity_gate':50,'gates':{'raw_gain_positive_all':True,'raw_gain_positive_primary_subset':True,'raw_beats_host':True,'raw_beats_compiler':True,'majority_folios_positive':True,'exact_max_three_p_le_005':True},'f84r':{'new_access':False,'actual_inputs_contain_rows':False,'prior_limited_audit_exposure_inherited':True},'inputs':{p:sha(ROOT/p) for p in FILES},'implementation':{Path(__file__).name:sha(Path(__file__))},'claim_ceiling':'Transferable raw source-string dependence for next-field extent only; no content host, record semantics, heading, recipe, semantic role, word, morpheme, POS, sound, language, plaintext, meaning, or translation.'};x['prediction_content_sha256']=csha(x);OUT.write_text(json.dumps(x,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':x['status'],'content_sha256':x['prediction_content_sha256']},sort_keys=True))
