#!/usr/bin/env python3
"""Freeze GDT292 before closure scoring."""
from __future__ import annotations
import csv,hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent;METHOD=R/'GDT292_RIGHT_FAMILY_CLOSURE_CHANNEL_METHOD.md';DESIGN=R/'gdt292_design.json';MAN=R/'gdt292_freeze_manifest.tsv';PANELS=['AUGSBURG_ACCOUNTS_1402_1424','ARBITRARY_LOCAL_CODEBOOK','COMPOSITIONAL_TECHNICAL_NOTATION','HYBRID_SHORTHAND','LATIN_SCHOLASTIC_GRAPHEMATIC','LATIN_MEDICAL_GRAPHEMATIC','LATIN_15C_GRAPHEMATIC','VOYNICH_REFERENCE'];ART=['gdt291_result.json','gdt291_validation.json','gdt290_result.json','gdt062_result.json','gdt278_native_event_inventory.tsv','gdt288_result.json']
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def csha(v):return hashlib.sha256(json.dumps(v,sort_keys=True,ensure_ascii=True,separators=(',',':')).encode()).hexdigest()
def main():
 with MAN.open('w',encoding='utf8',newline='') as h:w=csv.DictWriter(h,['artifact','frozen_sha256'],delimiter='\t',lineterminator='\n');w.writeheader();w.writerows([{'artifact':x,'frozen_sha256':sha(R/x)} for x in ART])
 d={'schema':'GDT292_RIGHT_FAMILY_CLOSURE_CHANNEL_DESIGN_V1','status':'FROZEN_BEFORE_GDT292_SCORING','panels':PANELS,'events_per_panel':8448,'outcome':'EXACT_DY_B3_LINE_CLOSE_PARAGRAPH_CLOSE_TUPLE','models':['LAYOUT_CONTEXT','EXACT_HOST','OUTER_LOCAL_CONTEXT','RIGHT_FAMILY'],'layout_context':['section','currier','hand','register','within_field_position','record_ordinal_bucket','field_ordinal_bucket','physical_group_position','host_length'],'outer_local_context':['exact_page_host','wrapper','local_frame','inner_d'],'primary_prior_mass':11.0,'voynich_prior_sensitivities':[5.0,22.0],'primary_split':'HELD_PHYSICAL_FOLIO','voynich_transfer_sensitivities':['HELD_SECTION','HELD_HAND'],'null_worlds':64,'null_seed':'GDT292_HELD_CLOSURE_ALIGNMENT','null_operation':'PERMUTE_HELD_CLOSURE_OUTCOMES_WITHIN_EXACT_FOLIO_LAYOUT_WRAPPER_FRAME_INNERD_STRATA_AFTER_PREDICTIONS_FREEZE','maxT':'MAX_STANDARDIZED_RIGHT_GAIN_OVER_NULL_VARIABLE_PANELS','zero_variance_rule':'DESCRIPTIVE_SCORE_WITH_P_VALUES_NA_AND_EXCLUDE_FROM_MAXT','decision':{'support':'RIGHT_FAMILY_CLOSURE_CHANNEL_SUPPORTED','fail':'RIGHT_FAMILY_CLOSURE_CHANNEL_WEAK_OR_LOCAL','minimum_positive_right_classes':4,'minimum_positive_folios':60,'require_section_and_hand_positive':True,'alpha':.05},'same_group_parser_coupled':True,'new_corpora':0,'new_architectures':0,'semantic_assignments':0,'claim_ceiling':'Formal right-family to closure association only; no suffix grammar name lexical class abbreviation sound language meaning plaintext or translation.','f84':{'input_files':0,'opened':False,'parsed':False,'retained':False,'joined':False,'scored':False},'freeze_manifest_sha256':sha(MAN),'method_sha256':sha(METHOD),'implementation':{'freeze_gdt292_right_family_closure_channel.py':sha(Path(__file__))}};d['content_sha256']=csha(d);DESIGN.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':d['status'],'content_sha256':d['content_sha256']},sort_keys=True))
if __name__=='__main__':main()
