#!/usr/bin/env python3
"""Freeze GDT290 before class scoring."""
from __future__ import annotations
import csv,hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent;METHOD=R/'GDT290_LATENT_HOST_RENDERER_CLASSES_METHOD.md';DESIGN=R/'gdt290_design.json';MAN=R/'gdt290_freeze_manifest.tsv'
PANELS=['AUGSBURG_ACCOUNTS_1402_1424','ARBITRARY_LOCAL_CODEBOOK','COMPOSITIONAL_TECHNICAL_NOTATION','HYBRID_SHORTHAND','LATIN_SCHOLASTIC_GRAPHEMATIC','LATIN_MEDICAL_GRAPHEMATIC','LATIN_15C_GRAPHEMATIC','VOYNICH_REFERENCE'];ART=['gdt289_result.json','gdt289_validation.json','gdt286_result.json','gdt278_native_event_inventory.tsv','gdt288_result.json']
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def csha(v):return hashlib.sha256(json.dumps(v,sort_keys=True,ensure_ascii=True,separators=(',',':')).encode()).hexdigest()
def main():
 with MAN.open('w',encoding='utf8',newline='') as h:w=csv.DictWriter(h,['artifact','frozen_sha256'],delimiter='\t',lineterminator='\n');w.writeheader();w.writerows([{'artifact':x,'frozen_sha256':sha(R/x)} for x in ART])
 d={'schema':'GDT290_LATENT_HOST_RENDERER_CLASSES_DESIGN_V1','status':'CAPACITY_CORRECTED_FROZEN_BEFORE_GDT290_SCORING','panels':PANELS,'events_per_panel':8448,'host_bucket_count':8,'host_bucket_seed':'GDT289_HOST_BUCKET','outcome':'FROZEN_WRAPPER_CLASS','primary_k':4,'voynich_sensitivity_k':[2,8],'minimum_training_hosts_per_class':3,'maximum_lloyd_iterations':30,'initialization':'SHA_MINIMUM_FIRST_CENTER_THEN_FARTHEST_FIRST_LEXICOGRAPHIC_TIES','features':'OPAQUE_HOST_OTHER_POSITION_NORMALIZED_WRAPPER_PROFILES_PLUS_MISSING_FLAGS','target_cell_rule':'FORBID_TARGET_HOST_TARGET_POSITION_PROFILE','training_exclusion':'HELD_FOLIO_AND_TARGET_HOST_BUCKET','cluster_target_estimator':'HOST_EQUAL_TARGET_POSITION_PROFILE_DIRICHLET_ONE_HALF','effective_count':'TARGET_HOST_OTHER_POSITION_OCCURRENCE_COUNT','hierarchical_prior_mass':11.0,'baseline':'GDT289_OTHER_POSITION_HOST_BAG','primary_split':'HELD_PHYSICAL_FOLIO','voynich_transfer_sensitivities':['HELD_SECTION','HELD_HAND'],'null_worlds':64,'null_seed':'GDT290_HELD_WRAPPER_ALIGNMENT','null_operation':'PERMUTE_HELD_WRAPPER_OUTCOMES_WITHIN_EXACT_FOLIO_REGISTER_POSITION_LENGTH_AND_HOST_EDGE_STRATA_AFTER_PREDICTIONS_FREEZE','maxT':'MAX_STANDARDIZED_K4_GAIN_OVER_NULL_VARIABLE_AND_K4_CAPABLE_PANELS','capacity_unscored_panels':['LATIN_SCHOLASTIC_GRAPHEMATIC'],'capacity_correction_evidence':'ONLY_PRIMARY_K4_SCOREABLE_ROW_COUNTS_EXPOSED_NO_EFFECT_OR_DECISION','zero_variance_rule':'DESCRIPTIVE_SCORE_WITH_P_VALUES_NA_AND_EXCLUDE_FROM_MAXT','minimum_voynich_scored_events':1000,'decision':{'support':'COMPACT_LATENT_HOST_RENDERER_CLASSES_SUPPORTED','fail':'HOST_POSITION_RENDERING_REMAINS_LEXICALIZED_OR_HIGH_CAPACITY','capacity':'INSUFFICIENT_LATENT_HOST_CLASS_CAPACITY','minimum_positive_host_buckets':6,'minimum_positive_positions':3,'require_held_section_and_hand_positive':True,'alpha':.05},'new_corpora':0,'new_architectures':0,'semantic_assignments':0,'page_host_substrings_mined':0,'claim_ceiling':'Compact opaque renderer classes only; no lexical class morphology function abbreviation sound language meaning plaintext or translation.','f84':{'input_files':0,'opened':False,'parsed':False,'retained':False,'joined':False,'scored':False},'freeze_manifest_sha256':sha(MAN),'method_sha256':sha(METHOD),'implementation':{'freeze_gdt290_latent_host_renderer_classes.py':sha(Path(__file__))}};d['content_sha256']=csha(d);DESIGN.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':d['status'],'content_sha256':d['content_sha256']},sort_keys=True))
if __name__=='__main__':main()
