#!/usr/bin/env python3
"""Freeze GDT132 before external target-pair enumeration or scoring."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parent;OUT=ROOT/'gdt132_prediction.json'
FILES=(ROOT/'GDT132_CROSS_REGISTER_CONTINUATION_ARITY_METHOD.md',ROOT/'gdt131_result.json',ROOT/'gdt127_q20_field_inventory.tsv',ROOT/'q20ob001_source_panel.tsv',ROOT/'gdt016_group_state_inventory.tsv',ROOT/'experiments/semantic_assumptions/results/source_separator_transcription.tsv',ROOT/'run_gdt012_core_semantic_atlas.py',ROOT/'run_gdt062_right_family_register_renderer.py')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def csha(v):return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest()
x={'schema':'GDT132_CROSS_REGISTER_CONTINUATION_ARITY_PREDICTION_V1','status':'FROZEN_BEFORE_EXTERNAL_TARGET_PAIR_ENUMERATION','training':'GDT131_ZL3b_170_Q20_RECORDS','external_selection':'COMPLETE_STRICT_PARAGRAPH_START_TO_IMMEDIATE_NEXT_NONSTART_LINE_SECTIONS_H_B_P_T_C_EXCLUDE_Q20_FOLIOS_AND_F84R','models':['REFERENCE','LAST_HOST_CHAR3_HASH32','LAST_RAW_CHAR3_HASH32'],'target':'FIRST_NEXT_LINE_FIELD_GROUP_COUNT_BIN_1_2_3_4PLUS','prediction':'LAST_HOST_CHAR3_HASH32_IMPROVES_EXTERNAL_TARGET_ABOVE_REFERENCE_AND_RAW','gates':{'host_gain_positive':True,'host_beats_raw':True,'majority_folios_positive':True,'max_two_p_le_005':True},'f84r':{'opened':False,'retained':False,'queried':False,'joined':False,'scored':False,'targeted':False},'inputs':{str(p.relative_to(ROOT)):sha(p) for p in FILES},'implementation':{Path(__file__).name:sha(Path(__file__))},'claim_ceiling':'Formal cross-register next-field extent only; no heading, recipe, semantic role, object, gloss, word, morpheme, POS, sound, language, plaintext, meaning, or translation.'};x['prediction_content_sha256']=csha(x);OUT.write_text(json.dumps(x,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':x['status'],'content_sha256':x['prediction_content_sha256']},sort_keys=True))
