#!/usr/bin/env python3
"""Score frozen B3/following-label distributed closure mechanisms."""
import csv,hashlib,json,math
from collections import defaultdict
from pathlib import Path
R=Path(__file__).resolve().parent
OLD=R/'gdt224_result.json';REC=R/'gdt224_record_role_summary.tsv';PROJ=R/'gdt224_field_role_projection.tsv';FRAME=R/'gdt046_line_frames.tsv';LABELS=R/'gdt012_annotated_core_inventory.tsv';FREEZE=R/'gdt225_prediction_freeze.json';FV=R/'gdt225_freeze_validation.json';METHOD=R/'GDT225_Q13_DISTRIBUTED_CLOSURE_FREEZE_METHOD.md';REPORT=R/'GDT225_Q13_DISTRIBUTED_CLOSURE_REPORT.md'
ATLAS=R/'gdt225_record_closure_atlas.tsv';SCORES=R/'gdt225_closure_scores.tsv';LOFO=R/'gdt225_lofo.tsv';COUNTER=R/'gdt225_counterexamples.tsv';RESULT=R/'gdt225_result.json';FREEZE_COMMIT='f9ed5f1'
def read(p):
 with p.open(encoding='utf8',newline='') as h:return list(csv.DictReader(h,delimiter='\t'))
def write(p,rows):
 with p.open('w',encoding='utf8',newline='') as h:w=csv.DictWriter(h,fieldnames=list(rows[0]),delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def csha(v):return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=True).encode()).hexdigest()
def fisher_greater(a,b,c,d):
 n=a+b+c+d;r1=a+b;c1=a+c;den=math.comb(n,r1);lo=max(0,r1-(n-c1));hi=min(r1,c1);return sum(math.comb(c1,x)*math.comb(n-c1,r1-x)/den for x in range(a,hi+1)) if lo<=a<=hi else 1
def rate(rows,key,cond=None,balanced=False):
 if cond is not None:rows=[r for r in rows if cond(r)]
 if not rows:return 0
 if not balanced:return sum(int(r[key]) for r in rows)/len(rows)
 fs=sorted({r['physical_folio'] for r in rows});return sum(sum(int(r[key]) for r in rows if r['physical_folio']==f)/sum(1 for r in rows if r['physical_folio']==f) for f in fs)/len(fs)
def main():
 freeze=json.loads(FREEZE.read_text());assert freeze['status']=='FROZEN_BEFORE_B3_AND_FOLLOWING_LABEL_JOIN'
 proj=read(PROJ);rec=read(REC);frames={r['locus']:r for r in read(FRAME) if not r['page'].startswith('f84')}
 labels=defaultdict(set)
 with LABELS.open() as h:
  for r in csv.DictReader(h,delimiter='\t'):
   assert not r['page'].startswith('f84')
   labels[r['page']].add(int(r['locus'].split('.')[1]))
 byrec=defaultdict(list);page_prose=defaultdict(set)
 for p in proj:assert not p['page'].startswith('f84');byrec[p['record_id']].append(p);page_prose[p['page']].add(int(p['locus'].split('.')[1]))
 atlas=[]
 for r in rec:
  last=max(byrec[r['record_id']],key=lambda z:int(z['field_ordinal']));end=int(last['locus'].split('.')[1]);later=sorted(x for x in page_prose[r['page']] if x>end);nxt=later[0] if later else None;labs=sorted(x for x in labels[r['page']] if x>end and (nxt is None or x<nxt));b3=int(frames[last['locus']]['b3_close']);fc=int(r['final_closer_like']);proxy=int(bool(b3 or labs));atlas.append({'scope':r['scope'],'page':r['page'],'physical_folio':r['physical_folio'],'record_id':r['record_id'],'field_count':r['field_count'],'final_prose_locus':last['locus'],'next_prose_locus':f"{r['page']}.{nxt}" if nxt is not None else 'PAGE_END','field_closer_like':fc,'missing_field_closer':1-fc,'final_line_b3':b3,'following_label_block':int(bool(labs)),'following_label_loci':'|'.join(f"{r['page']}.{x}" for x in labs) or 'NONE','source_gap_to_first_label':(labs[0]-end if labs else -1),'distributed_closure_proxy':proxy,'expanded_closure':int(bool(fc or proxy))})
 Q=[r for r in atlas if r['scope']=='Q13'];H=[r for r in atlas if r['scope']=='HERBAL_B2'];qm=rate(Q,'distributed_closure_proxy',lambda x:int(x['missing_field_closer']));hm=rate(H,'distributed_closure_proxy',lambda x:int(x['missing_field_closer']));qc=rate(Q,'distributed_closure_proxy',lambda x:int(x['field_closer_like']));base=rate(H,'field_closer_like',balanced=True)-rate(Q,'field_closer_like',balanced=True);expanded=rate(H,'expanded_closure',balanced=True)-rate(Q,'expanded_closure',balanced=True);shrink=(base-expanded)/base if base else 0
 rawbase=rate(H,'field_closer_like')-rate(Q,'field_closer_like');rawexp=rate(H,'expanded_closure')-rate(Q,'expanded_closure');rawshrink=(rawbase-rawexp)/rawbase if rawbase else 0
 qmis=[x for x in Q if int(x['missing_field_closer'])];hmis=[x for x in H if int(x['missing_field_closer'])];qcl=[x for x in Q if int(x['field_closer_like'])]
 p1=fisher_greater(sum(int(x['distributed_closure_proxy']) for x in qmis),sum(not int(x['distributed_closure_proxy']) for x in qmis),sum(int(x['distributed_closure_proxy']) for x in hmis),sum(not int(x['distributed_closure_proxy']) for x in hmis));p2=fisher_greater(sum(int(x['distributed_closure_proxy']) for x in qmis),sum(not int(x['distributed_closure_proxy']) for x in qmis),sum(int(x['distributed_closure_proxy']) for x in qcl),sum(not int(x['distributed_closure_proxy']) for x in qcl))
 score=[{'endpoint':'MISSING_PROXY_Q13_MINUS_HERBAL','q13_value':f'{qm:.12g}','herbal_value':f'{hm:.12g}','effect':f'{qm-hm:.12g}','direction_hit':int(qm>hm),'one_sided_fisher_p':f'{p1:.12g}'},{'endpoint':'Q13_PROXY_MISSING_MINUS_CLOSER','q13_value':f'{qm:.12g}','herbal_value':f'{qc:.12g}','effect':f'{qm-qc:.12g}','direction_hit':int(qm>qc),'one_sided_fisher_p':f'{p2:.12g}'},{'endpoint':'EXPANDED_CLOSURE_DEFICIT_SHRINK','q13_value':f'{base:.12g}','herbal_value':f'{expanded:.12g}','effect':f'{shrink:.12g}','direction_hit':int(shrink>=.5),'one_sided_fisher_p':'NOT_APPLICABLE'},{'endpoint':'RECORD_WEIGHTED_DEFICIT_SHRINK','q13_value':f'{rawbase:.12g}','herbal_value':f'{rawexp:.12g}','effect':f'{rawshrink:.12g}','direction_hit':int(rawshrink>=.5),'one_sided_fisher_p':'NOT_APPLICABLE'}]
 lofo=[]
 for f in sorted({r['physical_folio'] for r in Q}):
  q=[r for r in Q if r['physical_folio']!=f];a=rate(q,'distributed_closure_proxy',lambda x:int(x['missing_field_closer']),True)-rate(H,'distributed_closure_proxy',lambda x:int(x['missing_field_closer']),True);b=rate(q,'distributed_closure_proxy',lambda x:int(x['missing_field_closer']),True)-rate(q,'distributed_closure_proxy',lambda x:int(x['field_closer_like']),True);bd=rate(H,'field_closer_like',balanced=True)-rate(q,'field_closer_like',balanced=True);ed=rate(H,'expanded_closure',balanced=True)-rate(q,'expanded_closure',balanced=True);s=(bd-ed)/bd if bd else 0;lofo.append({'held_q13_folio':f,'missing_proxy_advantage':f'{a:.12g}','q13_missing_enrichment':f'{b:.12g}','deficit_shrink_fraction':f'{s:.12g}','all_three_hit':int(a>0 and b>0 and s>=.5)})
 gates={'q13_missing_proxy_higher':qm>hm,'q13_missing_enrichment':qm>qc,'record_weighted_half_deficit_reduction':rawshrink>=.5,'folio_balanced_half_deficit_reduction':shrink>=.5,'at_least_eight_lofo':sum(int(x['all_three_hit']) for x in lofo)>=8};status='DISTRIBUTED_CLOSURE_MECHANISM_PROVISIONAL' if all(gates.values()) else 'DISTRIBUTED_CLOSURE_PARTIAL_OR_GENERIC' if sum(gates.values())>=2 else 'DISTRIBUTED_CLOSURE_NOT_SUPPORTED'
 counter=[{'counterexample':'FOLIO_BALANCED_THRESHOLD_MISS','value':f'{shrink:.12g}','detail':'The record-weighted deficit shrinks by more than half, but folio balancing reduces this below the frozen 0.5 threshold.'},{'counterexample':'LOFO_INSTABILITY','value':f"{sum(int(x['all_three_hit']) for x in lofo)}_OF_{len(lofo)}",'detail':'The full three-gate direction does not survive enough q13 folio deletions.'},{'counterexample':'LABEL_NOT_SELECTIVE_FOR_MISSING','value':f"{sum(int(x['following_label_block']) for x in qmis)}/{len(qmis)}_VS_{sum(int(x['following_label_block']) for x in qcl)}/{len(qcl)}",'detail':'Following label blocks are not more frequent among q13 records missing a field closer.'},{'counterexample':'B3_LOW_CAPACITY','value':f"Q13_{sum(int(x['final_line_b3']) for x in Q)}_HERBAL_{sum(int(x['final_line_b3']) for x in H)}",'detail':'The B3 channel has too few records to explain the overall deficit alone.'},{'counterexample':'SOURCE_ORDER_NOT_OWNERSHIP','value':f"Q13_LABEL_BLOCKS_{sum(int(x['following_label_block']) for x in Q)}",'detail':'A label after prose in source order is not necessarily a closer or cross-reference.'}]
 write(ATLAS,atlas);write(SCORES,score);write(LOFO,lofo);write(COUNTER,counter)
 result={'schema':'GDT225_Q13_DISTRIBUTED_CLOSURE_RESULT_V1','status':status,'freeze_commit':FREEZE_COMMIT,'counts':{'q13_records':len(Q),'herbal_records':len(H),'q13_field_closers':sum(int(x['field_closer_like']) for x in Q),'herbal_field_closers':sum(int(x['field_closer_like']) for x in H),'q13_b3':sum(int(x['final_line_b3']) for x in Q),'herbal_b3':sum(int(x['final_line_b3']) for x in H),'q13_following_label_blocks':sum(int(x['following_label_block']) for x in Q),'herbal_following_label_blocks':sum(int(x['following_label_block']) for x in H),'q13_proxies':sum(int(x['distributed_closure_proxy']) for x in Q),'herbal_proxies':sum(int(x['distributed_closure_proxy']) for x in H),'q13_expanded_closures':sum(int(x['expanded_closure']) for x in Q),'herbal_expanded_closures':sum(int(x['expanded_closure']) for x in H)},'effects':{'missing_proxy_q13_minus_herbal':qm-hm,'q13_proxy_missing_minus_field_closer':qm-qc,'record_weighted_baseline_deficit':rawbase,'record_weighted_expanded_deficit':rawexp,'record_weighted_deficit_shrink':rawshrink,'folio_balanced_baseline_deficit':base,'folio_balanced_expanded_deficit':expanded,'folio_balanced_deficit_shrink':shrink},'lofo_all_three_hits':sum(int(x['all_three_hit']) for x in lofo),'lofo_total':len(lofo),'gates':gates,'interpretation':'Existing B3 and following-label channels partially reduce the q13 closer deficit, but the mechanism is not folio-stable or specifically concentrated in missing closers.','claim_ceiling':'Formal/source-order distributed-closure diagnostic only; no label key index word meaning language plaintext or translation.','f84':{'accessed':False,'retained':False,'joined':False,'scored':False},'inputs':{p.name:sha(p) for p in (OLD,REC,PROJ,FRAME,LABELS,FREEZE,FV)},'implementation':{Path(__file__).name:sha(Path(__file__))},'outputs':{p.name:sha(p) for p in (ATLAS,SCORES,LOFO,COUNTER)},'documents':{METHOD.name:sha(METHOD),REPORT.name:sha(REPORT)}};result['result_content_sha256']=csha(result);RESULT.write_text(json.dumps(result,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':status,'counts':result['counts'],'effects':result['effects'],'lofo':result['lofo_all_three_hits']},sort_keys=True))
if __name__=='__main__':main()
