#!/usr/bin/env python3
"""Build the evidence-bound GDT308 sparse-operation grammar synthesis."""
import csv,hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent;REPORT=R/'GDT308_SPARSE_OPERATION_HYBRID_GRAMMAR_REPORT.md';MODEL=R/'gdt308_operational_grammar.json';COUNTER=R/'gdt308_counterexamples.tsv';RESULT=R/'gdt308_result.json'
INPUTS=[R/f'gdt{x}_result.json' for x in (298,300,303,305,306,307)];SCORES=R/'gdt307_domain_scores.tsv'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def can(v):return hashlib.sha256(json.dumps(v,sort_keys=True,ensure_ascii=True,separators=(',',':')).encode()).hexdigest()
def read(p):
 with Path(p).open(encoding='utf8',newline='') as h:return list(csv.DictReader(h,delimiter='\t'))
def write(p,rows):
 with Path(p).open('w',encoding='utf8',newline='') as h:w=csv.DictWriter(h,rows[0].keys(),delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows)
def main():
 prior={p.name:json.loads(p.read_text()) for p in INPUTS};assert prior['gdt303_result.json']['status']=='RENDERER_OPERATION_POSITION_DELTAS_FOUND';assert prior['gdt307_result.json']['classifications']=={'wrapper:NONE>q':'DOMAIN_MIXED_OR_UNSTABLE','wrapper:ch>s':'DOMAIN_STABLE','wrapper:d>s':'DOMAIN_STABLE'};scores={(x['operation'],x['domain_type']):x for x in read(SCORES)}
 model={'schema':'GDT308_SPARSE_OPERATION_HYBRID_GRAMMAR_V1','status':'SPARSE_OPERATION_LEXICALIZED_HYBRID_GRAMMAR','world_ranking':['LEXICALIZED_HYBRID_RECORD_SHORTHAND_WITH_SPARSE_SHARED_OPERATIONS','ABBREVIATION_HEAVY_NATURAL_LANGUAGE_COMPONENT','NONSEMANTIC_STRING_STATISTICAL_PROCESS','COMPACT_FACTORIAL_NOTATION','FIXED_LOCAL_CODEBOOK'],'generator':['PAGE_OR_REGISTER','RECORD_TEMPLATE_AND_LINE_ENTRY_STATE','FIELD_OPPORTUNITY_AND_COARSE_POSITION','UNKNOWN_LATENT_PAYLOAD_OR_FORM_ENTRY','JOINT_PAGE_HOST_RENDERER_SURFACE_ALTERNANT','OPTIONAL_COMPATIBILITY_LICENSED_SHARED_OPERATION','LOCAL_FRAME_RIGHT_EDGE_AND_CLOSURE_BACKOFF','VISIBLE_SOURCE_GROUP'],'line_grammar':{'LINE':'CLOSED_FIELD* OPEN_TAIL?','CLOSED_FIELD':'FIELD_PAYLOAD DY','POST_DY_ENTRY':'Q_WRAPPER_ENRICHED_BUT_HOST_REGISTER_CONDITIONED','PHYSICAL_RESET':'LINE_START'},'shared_operations':[{'operation':'wrapper:ch>s','formal_effect':'MOVE_MASS_FROM_MIDDLE_TO_PHYSICAL_BOUNDARY','domain_stability':'DOMAIN_STABLE','section_accuracy':scores[('wrapper:ch>s','section')]['direction_accuracy'],'hand_accuracy':scores[('wrapper:ch>s','hand')]['direction_accuracy']},{'operation':'wrapper:d>s','formal_effect':'SHIFT_MAINLY_TOWARD_PHYSICAL_FIRST','domain_stability':'DOMAIN_STABLE','section_accuracy':scores[('wrapper:d>s','section')]['direction_accuracy'],'hand_accuracy':scores[('wrapper:d>s','hand')]['direction_accuracy']},{'operation':'wrapper:NONE>q','formal_effect':'POST_DY_ENTRY_ECOLOGY_WITH_DOMAIN_MIXED_POSITION_VECTOR','domain_stability':'DOMAIN_MIXED_OR_UNSTABLE','section_accuracy':scores[('wrapper:NONE>q','section')]['direction_accuracy'],'hand_accuracy':scores[('wrapper:NONE>q','hand')]['direction_accuracy']}],'compatibility_rule':'OPERATIONS_APPLY_ONLY_TO_OBSERVED_OR_TRAINABLE_HOST_RENDERER_NEIGHBORHOODS; NO_GLOBAL_PRODUCTIVE_AFFIX_TABLE','semantic_assignments':0,'f84_authorized':False,'claim_ceiling':'Formal sparse-operation hybrid grammar only; no word morpheme grammar meaning sound language plaintext or translation.'};model['content_sha256']=can(model);MODEL.write_text(json.dumps(model,indent=2,sort_keys=True)+'\n')
 counter=[{'counterexample_id':'C01','finding':'GDT300 shared renderer worsens held-folio placement by 0.031736 bits/event.','impact':'Most renderer behavior remains host-specific; sparse operations cannot become a global affix grammar.'},{'counterexample_id':'C02','finding':'GDT303 transfers only 3 of 29 powered operations.','impact':'Productivity is exceptional and compatibility-conditioned.'},{'counterexample_id':'C03','finding':'GDT305 low-support s panels contain only two and five hosts.','impact':'Rare-form generalization of s remains weak despite frequent-form domain stability.'},{'counterexample_id':'C04','finding':'GDT306 replicates prior post-DY qo ecology and GDT307 finds q position domain-mixed.','impact':'q is not one context-free positional operator.'},{'counterexample_id':'C05','finding':'Every operation target is a physical/parser role rather than readable content.','impact':'No semantics or translation follows.'},{'counterexample_id':'C06','finding':'No admissible repeated referent anchor exists.','impact':'The latent payload remains unidentified.'},{'counterexample_id':'C07','finding':'No f84 input is used.','impact':'The sealed holdout remains untouched.'}];write(COUNTER,counter)
 report=['# GDT308 — sparse-operation hybrid grammar update','', 'Status: **SPARSE_OPERATION_LEXICALIZED_HYBRID_GRAMMAR**.','', 'This is an abductive, evidence-bound synthesis. It scores no new manuscript row and assigns no meaning.','', '## Revised executable generator','', '```text','PAGE / REGISTER','  -> RECORD TEMPLATE + LINE-ENTRY STATE','  -> FIELD OPPORTUNITY / COARSE POSITION','  -> UNKNOWN LATENT PAYLOAD OR FORM ENTRY','  -> JOINT (PAGE_HOST, RENDERER) SURFACE ALTERNANT','  -> OPTIONAL COMPATIBILITY-LICENSED SHARED OPERATION','  -> LOCAL FRAME + RIGHT EDGE + DY/B3 CLOSURE BACKOFF','  -> VISIBLE SOURCE GROUP','```','','The revision to GDT298 is narrow but real: rendering is not entirely an exception table. A small shared operation layer exists inside a much larger host-specific alternant lexicon.','','## Current shared operations','','| operation | formal effect | section/hand direction accuracy | status |','|---|---|---:|---|']
 for x in model['shared_operations']:report.append(f"| `{x['operation']}` | {x['formal_effect']} | {float(x['section_accuracy']):.3f}/{float(x['hand_accuracy']):.3f} | {x['domain_stability']} |")
 report+=['','## Field/line grammar','', '```text','LINE         := CLOSED_FIELD* OPEN_TAIL?','CLOSED_FIELD := FIELD_PAYLOAD DY','POST_DY      := q-enriched entry ecology (host/register conditioned)','RESET        := physical line start','```','','`ch->s` and `d->s` are the first sparse renderer operations to survive unseen-host and held-domain checks. `NONE->q` generalizes as post-DY ecology but not as one invariant domain-wide physical-position vector. This combination explains why the global renderer model fails while a few exact transformations remain reusable.','','## Novel predictions','','1. New compatible `ch/s` and `d/s` exact-form pairs should preserve the respective boundary/initial delta even when their host was not used to estimate it.','2. A compatibility model that first predicts whether an operation is licensed should beat both a global renderer and a pure exact-form table; applying operations indiscriminately should lose.','3. q enrichment should recur after DY across new forms, but its physical FIRST/MIDDLE/LAST vector should change by register/host ecology.','4. Complete-form identity should retain placement information outside the three supported operation neighborhoods.','5. Any eventual payload decoder must marginalize over joint form alternants plus this sparse operation layer rather than stripping every wrapper uniformly.','','## What remains awkward','', '- The operation family was discovered and selected post hoc before domain stability testing.','- Only three of 29 powered operations transfer; no compact full compiler has emerged.','- The payload carrier remains unidentified and no external referent maps to a form.','- Historical architecture controls do not uniquely distinguish shorthand, language-derived abbreviation, and technical notation.','','## Claim ceiling','',model['claim_ceiling']+' No f84 material was accessed.'];REPORT.write_text('\n'.join(report)+'\n');res={'schema':'GDT308_SPARSE_OPERATION_GRAMMAR_RESULT_V1','status':model['status'],'summary':{'shared_operations':3,'domain_stable_operations':2,'semantic_assignments':0},'claim_ceiling':model['claim_ceiling'],'f84':{'input_files':0,'opened':False,'parsed':False,'retained':False,'joined':False,'scored':False},'inputs':{p.name:sha(p) for p in INPUTS+[SCORES]},'implementation':{Path(__file__).name:sha(Path(__file__))},'outputs':{p.name:sha(p) for p in (MODEL,COUNTER,REPORT)}};res['content_sha256']=can(res);RESULT.write_text(json.dumps(res,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':res['status'],'model':MODEL.name},sort_keys=True))
if __name__=='__main__':main()
