#!/usr/bin/env python3
"""Score the frozen GDT124 OPEN:ar prediction on excluded f106r rows."""
import csv,hashlib,json,math
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parent;PRED=ROOT/'gdt124_prediction.json';FREEZE=ROOT/'gdt124_frozen_predictions.tsv';TARGET=ROOT/'experiments/semantic_assumptions/star_morphology_entry/source_panel.tsv';METHOD=ROOT/'GDT124_Q20_AR_RAY_TRANSFER_METHOD.md';REPORT=ROOT/'GDT124_Q20_AR_RAY_TRANSFER_REPORT.md';SCORES=ROOT/'gdt124_f106r_ar_ray_predictions.tsv';COUNTER=ROOT/'gdt124_f106r_ar_ray_counterexamples.tsv';RESULT=ROOT/'gdt124_result.json'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def csha(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()
def read(p):
 with Path(p).open(encoding='utf-8',newline='') as h:return list(csv.DictReader(h,delimiter='\t'))
def write(p,rows):
 fields=[]
 for r in rows:
  for k in r:
   if k not in fields:fields.append(k)
 with Path(p).open('w',encoding='utf-8',newline='') as h:w=csv.DictWriter(h,fieldnames=fields,delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows)
def metrics(rows,key):
 z=[r for r in rows if r[key] in ('7','8') and r['actual_rays'] in ('7','8')];hits=sum(r[key]==r['actual_rays'] for r in z);actual=Counter(r['actual_rays'] for r in z);major=max(actual.values()) if actual else 0;return {'eligible':len(z),'hits':hits,'accuracy':hits/len(z) if z else 0.,'majority_baseline_hits':major,'majority_baseline_accuracy':major/len(z) if z else 0.,'actual_7':actual['7'],'actual_8':actual['8']}
def main():
 p=json.loads(PRED.read_text());assert p['status']=='FROZEN_BEFORE_F106R_ROW_TARGET_JOIN';fr=read(FREEZE);target={int(r['star_ordinal']):r for r in read(TARGET) if r['page']=='f106r'};assert len(target)==15 and set(target)==set(range(1,16));out=[]
 for r in fr:
  q=target[int(r['star_ordinal'])];out.append({**r,'actual_rays':q['rays'],'actual_color':q['color'],'actual_tail':q['tail'],'target_provenance':'EXISTING_HUMAN_ANNOTATION_STOLFI_STAR_PROPS','primary_eligible':int(r['predicted_rays'] in ('7','8') and q['rays'] in ('7','8')),'primary_hit':int(r['predicted_rays'] in ('7','8') and r['predicted_rays']==q['rays']),'zl_prediction':'7' if r['zl_ar']=='1' else '8','it_prediction':'7' if r['it_ar']=='1' else '8','rf_prediction':'7' if r['rf_ar']=='1' else '8'})
 primary=metrics(out,'predicted_rays');sens={'ZL3b':metrics(out,'zl_prediction'),'IT2a':metrics(out,'it_prediction'),'RF1b':metrics(out,'rf_prediction')};pos=next(r for r in out if r['star_ordinal']=='13');directional=pos['actual_rays']=='7';one_sided=(primary['actual_7']/primary['eligible']) if directional and primary['eligible'] else 1.;primary['one_sided_single_positive_hypergeometric_p']=one_sided;primary['ordinal13_actual_rays']=int(pos['actual_rays']);primary['ordinal13_directional_hit']=directional;primary['improvement_over_majority_hits']=primary['hits']-primary['majority_baseline_hits']
 status='Q20_AR_RAY_PROSPECTIVE_DIRECTIONAL_HIT_BUT_UNDERPOWERED' if directional else 'Q20_AR_RAY_PROSPECTIVE_TRANSFER_FAILED';counter=[{'star_ordinal':r['star_ordinal'],'unit_id':r['unit_id'],'prediction_state':r['prediction_state'],'predicted_rays':r['predicted_rays'],'actual_rays':r['actual_rays'],'counterexample':'PRIMARY_MISS' if r['primary_eligible']=='1' and r['primary_hit']=='0' else 'READING_UNCERTAIN_EXCLUDED' if r['prediction_state']=='READING_UNCERTAIN' else 'NONE'} for r in out if not int(r['primary_hit'])]
 write(SCORES,out);write(COUNTER,counter)
 report=f'''# GDT124 — prospective f106r transfer of OPEN `ar`\n\nStatus: **{status}**\n\nThe frozen positive prediction was specific: f106r ordinal 13 should have 7 rays. It has **{pos['actual_rays']}**, so the directional cell {'hits' if directional else 'fails'}. Across the 11 all-reading-consensus predictions, {primary['hits']}/{primary['eligible']} exact 7/8 calls are correct versus {primary['majority_baseline_hits']}/{primary['eligible']} for the target-panel majority class. Actual counts are {primary['actual_7']} seven-ray and {primary['actual_8']} eight-ray; the one-positive conditional direction diagnostic is p={one_sided:.4f}.\n\n| reading rule | hits / eligible | accuracy | majority accuracy |\n|---|---:|---:|---:|\n'''+''.join(f"| {e} | {z['hits']}/{z['eligible']} | {z['accuracy']:.3f} | {z['majority_baseline_accuracy']:.3f} |\n" for e,z in sens.items())+'''\nThis is a real frozen-cell transfer, but it is not strong evidence: the hypothesis was selected from 843 discovery tests, its training max-search p was 1.0, the held primary has only one host-positive record, and the repository target file was not a pristine blind source. The specific directional cell failed and the complete primary rule is worse than the majority baseline, so `OPEN:ar` is rejected as a ray-count codeword. That failure does not alter `ar` as a formal PAGE_HOST. No “seven,” “ray,” “star,” role, number, word, morpheme, POS, sound, language, plaintext, meaning, or translation follows. f84r remained fully sealed and unpredicted.\n''';REPORT.write_text(report,encoding='utf-8')
 result={'schema':'GDT124_Q20_AR_RAY_TRANSFER_RESULT_V1','status':status,'target_page':'f106r','frozen_predictions':14,'primary':primary,'reading_sensitivities':sens,'postselection_context':{'discovery_tests':843,'training_local_p':0.003173053454,'training_max_library_p':1.0,'target_positive_records':1,'pristine_blind':False},'interpretation':'Prospective, provenance-qualified transfer of one postselected exact PAGE_HOST/visual-state direction.','claim_ceiling':'Visual/formal lead only; no star, ray, number, role, word, morpheme, POS, sound, language, plaintext, meaning or translation.','f84r':{'opened':False,'retained':False,'queried':False,'joined':False,'scored':False,'targeted':False,'assigned':False,'predicted':False},'inputs':{PRED.name:sha(PRED),FREEZE.name:sha(FREEZE),'gdt124_prediction_validation.json':sha(ROOT/'gdt124_prediction_validation.json'),str(TARGET.relative_to(ROOT)):sha(TARGET),'gdt123_result.json':sha(ROOT/'gdt123_result.json')},'implementation':{Path(__file__).name:sha(Path(__file__))},'outputs':{SCORES.name:sha(SCORES),COUNTER.name:sha(COUNTER)},'documents':{METHOD.name:sha(METHOD),REPORT.name:sha(REPORT)}};result['result_content_sha256']=csha(result);RESULT.write_text(json.dumps(result,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':status,'primary':primary,'sensitivities':sens},sort_keys=True))
if __name__=='__main__':main()
