#!/usr/bin/env python3
"""Build disclosed post-hoc GDT304 endpoint decomposition."""
import csv,hashlib,json
from collections import defaultdict
from pathlib import Path
R=Path(__file__).resolve().parent;SOURCE=R/'gdt278_native_event_inventory.tsv';PAIR=R/'gdt303_pair_deltas.tsv';METHOD=R/'GDT304_WRAPPER_FIELD_ENTRY_HYPOTHESIS_METHOD.md';REPORT=R/'GDT304_WRAPPER_FIELD_ENTRY_HYPOTHESIS_REPORT.md';OUT=R/'gdt304_endpoint_deltas.tsv';PRED=R/'gdt304_frozen_future_predictions.json';COUNTER=R/'gdt304_counterexamples.tsv';RESULT=R/'gdt304_result.json';OPS=('wrapper:ch>s','wrapper:d>s','wrapper:NONE>q')
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def can(v):return hashlib.sha256(json.dumps(v,sort_keys=True,ensure_ascii=True,separators=(',',':')).encode()).hexdigest()
def rcan(v):q=dict(v);q.pop('content_sha256',None);return can(q)
def read(p):
 with Path(p).open(encoding='utf8',newline='') as h:return list(csv.DictReader(h,delimiter='\t'))
def write(p,rows):
 with Path(p).open('w',encoding='utf8',newline='') as h:w=csv.DictWriter(h,rows[0].keys(),delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows)
def main():
 rows=read(SOURCE);assert not any(x['page'].startswith('f84') or x['locus'].startswith('f84') for x in rows);D=defaultdict(list)
 for x in rows:
  if x['control_id']=='VOYNICH_REFERENCE':D[(x['page_host'],x['source_surface_sha256'])].append(x)
 pairs=[x for x in read(PAIR) if x['operation'] in OPS];F={'LINE_FIRST':lambda x:int(x['group_index'])==1,'LINE_LAST':lambda x:int(x['group_index'])==int(x['group_count']),'FIELD_FIRST':lambda x:x['within_field_position']=='FIRST','FIELD_LAST':lambda x:x['within_field_position']=='LAST','RECORD_ORDINAL_1':lambda x:int(x['record_ordinal'])==1,'FIELD_ORDINAL_1':lambda x:int(x['field_ordinal'])==1,'LINE_CLOSE':lambda x:x['line_close']=='1','PARAGRAPH_CLOSE':lambda x:x['paragraph_close']=='1'};host=defaultdict(lambda:defaultdict(list))
 for p in pairs:
  a=D[(p['page_host'],p['source_surface_sha256'])];b=D[(p['page_host'],p['target_surface_sha256'])]
  for n,f in F.items():host[(p['operation'],p['page_host'])][n].append(sum(f(x) for x in b)/len(b)-sum(f(x) for x in a)/len(a))
 out=[]
 for op in OPS:
  H=sorted(h for o,h in host if o==op)
  for n in F:
   v=[sum(host[(op,h)][n])/len(host[(op,h)][n]) for h in H];out.append({'operation':op,'endpoint':n,'hosts':len(H),'mean_delta':f'{sum(v)/len(v):.12f}','positive_hosts':sum(x>0 for x in v),'negative_hosts':sum(x<0 for x in v),'zero_hosts':sum(x==0 for x in v),'provenance':'POSTHOC_ENDPOINT_INSPECTED_BEFORE_METHOD_PUBLICATION'})
 q={(x['operation'],x['endpoint']):x for x in out};gates={'all_three_field_first_positive':all(float(q[(o,'FIELD_FIRST')]['mean_delta'])>0 for o in OPS),'q_field_last_negative':float(q[('wrapper:NONE>q','FIELD_LAST')]['mean_delta'])<0,'record1_absolute_deltas_below_0_10':all(abs(float(q[(o,'RECORD_ORDINAL_1')]['mean_delta']))<.1 for o in OPS)};status='FIELD_ENTRY_WRAPPER_HYPOTHESIS_GENERATED_POSTHOC' if all(gates.values()) else 'FIELD_ENTRY_WRAPPER_HYPOTHESIS_NOT_COHERENT';pred={'schema':'GDT304_FROZEN_FUTURE_PREDICTIONS_V1','status':'FROZEN_AFTER_POSTHOC_HYPOTHESIS_GENERATION','predictions':[{'id':'P1','operation':'wrapper:NONE>q','prediction':'FIELD_FIRST_DELTA_POSITIVE_AND_FIELD_LAST_DELTA_NEGATIVE'},{'id':'P2','operation':'wrapper:ch>s','prediction':'FIELD_FIRST_DELTA_POSITIVE'},{'id':'P3','operation':'wrapper:d>s','prediction':'FIELD_FIRST_DELTA_POSITIVE'},{'id':'P4','operation':'ALL_THREE','prediction':'NO_CONSISTENT_RECORD_ORDINAL_1_SELECTION'}],'validation_requirement':'GENUINELY_NEW_UNEXPOSED_MATCHED_HOST_PANEL','f84_authorized':False};PRED.write_text(json.dumps(pred,indent=2,sort_keys=True)+'\n');counter=[{'counterexample_id':'C01','finding':'All endpoint values were inspected before GDT304 was written.','impact':'This is hypothesis generation, never confirmation.'},{'counterexample_id':'C02','finding':'ch-to-s includes a positive mean LINE_LAST delta.','impact':'s is not an exclusively line-initial marker.'},{'counterexample_id':'C03','finding':'q effect is small and reverses on some hosts.','impact':'q is a probabilistic renderer, not a deterministic prefix key.'},{'counterexample_id':'C04','finding':'FIELD_FIRST/FIELD_LAST are HPR2 parser outputs.','impact':'Physical line entry is the independent anchor.'},{'counterexample_id':'C05','finding':'No operation consistently selects record ordinal 1.','impact':'Do not gloss the wrapper as title, first record, or sequence number.'},{'counterexample_id':'C06','finding':'No f84 row occurs in the source.','impact':'The seal remains intact.'}];write(OUT,out);write(COUNTER,counter);report=['# GDT304 — wrapper field-entry hypothesis','',f'Status: **{status}**.','', '> This is post-hoc hypothesis generation: endpoint values were inspected before the method was published.','', '| operation | line Δ first/last | field Δ first/last | record-1 Δ | field-1 Δ |','|---|---:|---:|---:|---:|']
 for o in OPS:report.append(f"| `{o}` | {float(q[(o,'LINE_FIRST')]['mean_delta']):+.3f}/{float(q[(o,'LINE_LAST')]['mean_delta']):+.3f} | {float(q[(o,'FIELD_FIRST')]['mean_delta']):+.3f}/{float(q[(o,'FIELD_LAST')]['mean_delta']):+.3f} | {float(q[(o,'RECORD_ORDINAL_1')]['mean_delta']):+.3f} | {float(q[(o,'FIELD_ORDINAL_1')]['mean_delta']):+.3f} |")
 report+=['','## Leading formal hypothesis','', '`q` and `s` participate in probabilistic field-entry rendering. The s substitutions produce a large line/field-entry shift; q produces a smaller but broad entry-over-exit shift. Neither behaves like a record-ordinal-1 marker. Because ch→s can also raise line-last probability, s is better described as boundary-favoring with a strong entry bias than as an exclusively initial marker.','', 'The four exact predictions are frozen in `gdt304_frozen_future_predictions.json`; no currently exposed panel can validate them.','','## Claim ceiling','', 'Formal field-entry rendering hypothesis only; no grammatical category, POS, discourse meaning, morpheme, sound, language, plaintext, or translation. No f84 access.'];REPORT.write_text('\n'.join(report)+'\n');outputs=[OUT,PRED,COUNTER,REPORT];inputs=['gdt278_native_event_inventory.tsv','gdt303_pair_deltas.tsv','gdt303_result.json','gdt302_result.json'];res={'schema':'GDT304_WRAPPER_FIELD_ENTRY_HYPOTHESIS_RESULT_V1','status':status,'provenance':'POSTHOC_ENDPOINTS_INSPECTED_BEFORE_METHOD','gates':gates,'semantic_assignments':0,'claim_ceiling':'Formal probabilistic field-entry renderer hypothesis only; no grammatical semantic sound language plaintext or translation.','f84':{'input_files':0,'opened':False,'parsed':False,'retained':False,'joined':False,'scored':False},'inputs':{x:sha(R/x) for x in inputs},'documents':{METHOD.name:sha(METHOD),REPORT.name:sha(REPORT)},'implementation':{Path(__file__).name:sha(Path(__file__))},'outputs':{x.name:sha(x) for x in outputs}};res['content_sha256']=rcan(res);RESULT.write_text(json.dumps(res,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':status,'gates':gates},sort_keys=True))
if __name__=='__main__':main()
