#!/usr/bin/env python3
"""Score held-domain stability of the three GDT303 renderer operations."""
import csv,hashlib,json,math,statistics
from collections import Counter,defaultdict
from pathlib import Path
R=Path(__file__).resolve().parent;SOURCE=R/'gdt278_native_event_inventory.tsv';FROZEN=R/'gdt307_frozen_domain_cells.tsv';DESIGN=R/'gdt307_design.json';METHOD=R/'GDT307_RENDERER_OPERATION_DOMAIN_STABILITY_METHOD.md';PAIR=R/'gdt307_pair_domain_vectors.tsv';CELL=R/'gdt307_host_domain_vectors.tsv';SCORES=R/'gdt307_domain_scores.tsv';NULL=R/'gdt307_null_max.tsv';COUNTER=R/'gdt307_counterexamples.tsv';REPORT=R/'GDT307_RENDERER_OPERATION_DOMAIN_STABILITY_REPORT.md';RESULT=R/'gdt307_result.json';Y=('FIRST','MIDDLE','LAST')
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def can(v):return hashlib.sha256(json.dumps(v,sort_keys=True,ensure_ascii=True,separators=(',',':')).encode()).hexdigest()
def read(p):
 with Path(p).open(encoding='utf8',newline='') as h:return list(csv.DictReader(h,delimiter='\t'))
def write(p,rows):
 with Path(p).open('w',encoding='utf8',newline='') as h:w=csv.DictWriter(h,rows[0].keys(),delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows)
def role(x):
 i=int(x['group_index']);n=int(x['group_count']);return 'FIRST' if i==1 else 'LAST' if i==n else 'MIDDLE'
def delta(a,b):
 ca=Counter(role(x) for x in a);cb=Counter(role(x) for x in b);return tuple(cb[y]/len(b)-ca[y]/len(a) for y in Y)
def sign(seed,w,test,cell):return 1 if int(hashlib.sha256(f'{seed}|{w}|{test}|{cell}'.encode()).hexdigest()[:16],16)&1 else -1
def main():
 d=json.loads(DESIGN.read_text());stored=d.pop('content_sha256');assert stored==can(d) and d['status']=='FROZEN_BEFORE_DOMAIN_POSITION_SCORING';frozen=read(FROZEN);wanted={(x['page_host'],x['source_surface_sha256']) for x in frozen}|{(x['page_host'],x['target_surface_sha256']) for x in frozen};events=defaultdict(list);f84=0
 with SOURCE.open(encoding='utf8',newline='') as h:
  for x in csv.DictReader(h,delimiter='\t'):
   if x['control_id']!='VOYNICH_REFERENCE':continue
   f84+=x['page'].startswith('f84') or x['locus'].startswith('f84');key=(x['page_host'],x['source_surface_sha256'])
   if key in wanted:events[key].append(x)
 assert not f84;pairrows=[];hv=defaultdict(list)
 for c in frozen:
  dt=c['domain_type'];held=c['held_domain'];a=events[(c['page_host'],c['source_surface_sha256'])];b=events[(c['page_host'],c['target_surface_sha256'])];ah=[x for x in a if x[dt]==held];at=[x for x in a if x[dt]!=held];bh=[x for x in b if x[dt]==held];bt=[x for x in b if x[dt]!=held];assert (len(at),len(bt),len(ah),len(bh))==tuple(int(c[k]) for k in ('source_train_events','target_train_events','source_held_events','target_held_events'));tr=delta(at,bt);he=delta(ah,bh);dot=sum(x*y for x,y in zip(tr,he));row={**c,'train_delta_first':f'{tr[0]:.12f}','train_delta_middle':f'{tr[1]:.12f}','train_delta_last':f'{tr[2]:.12f}','held_delta_first':f'{he[0]:.12f}','held_delta_middle':f'{he[1]:.12f}','held_delta_last':f'{he[2]:.12f}','train_held_dot':f'{dot:.12f}'};pairrows.append(row);hv[(c['operation'],dt,held,c['page_host'])].append((tr,he))
 cellrows=[];vectors={}
 for key,vals in sorted(hv.items()):
  tr=tuple(statistics.mean(v[0][i] for v in vals) for i in range(3));he=tuple(statistics.mean(v[1][i] for v in vals) for i in range(3));dot=sum(x*y for x,y in zip(tr,he));cid='|'.join(key);vectors[key]=(tr,he,dot);cellrows.append({'operation':key[0],'domain_type':key[1],'held_domain':key[2],'page_host':key[3],'pairs':len(vals),'train_delta_first':f'{tr[0]:.12f}','train_delta_middle':f'{tr[1]:.12f}','train_delta_last':f'{tr[2]:.12f}','held_delta_first':f'{he[0]:.12f}','held_delta_middle':f'{he[1]:.12f}','held_delta_last':f'{he[2]:.12f}','train_held_dot':f'{dot:.12f}','direction_correct':int(dot>0),'cell_key_sha256':hashlib.sha256(cid.encode()).hexdigest()})
 tests=sorted({(x['operation'],x['domain_type']) for x in frozen});obs={};null={t:[] for t in tests}
 for t in tests:
  z=[(k,v) for k,v in vectors.items() if k[:2]==t];obs[t]=statistics.mean(v[2] for k,v in z)
 for w in range(d['null_worlds']):
  for t in tests:
   z=[sign(d['null_seed'],w,'|'.join(t),'|'.join(k))*v[2] for k,v in vectors.items() if k[:2]==t];null[t].append(statistics.mean(z))
 mu={t:statistics.mean(v) for t,v in null.items()};sd={t:statistics.pstdev(v) for t,v in null.items()};zs={t:(obs[t]-mu[t])/sd[t] if sd[t] else 0 for t in tests};maxz=[max((null[t][w]-mu[t])/sd[t] if sd[t] else 0 for t in tests) for w in range(d['null_worlds'])];scores=[]
 for t in tests:
  z=[(k,v) for k,v in vectors.items() if k[:2]==t];correct=sum(v[2]>0 for k,v in z);lp=(1+sum(x>=obs[t]-1e-15 for x in null[t]))/(1+d['null_worlds']);mp=(1+sum(x>=zs[t]-1e-15 for x in maxz))/(1+d['null_worlds']);scores.append({'operation':t[0],'domain_type':t[1],'host_domain_cells':len(z),'held_domains':len({k[2] for k,v in z}),'hosts':len({k[3] for k,v in z}),'mean_train_held_dot':f'{obs[t]:.12f}','direction_correct_cells':correct,'direction_accuracy':f'{correct/len(z):.12f}','null_mean':f'{mu[t]:.12f}','null_sd':f'{sd[t]:.12f}','standardized_score':f'{zs[t]:.12f}','local_p':f'{lp:.12f}','max12_p':f'{mp:.12f}'})
 sm={(x['operation'],x['domain_type']):x for x in scores};classes={}
 for op in d['operations']:
  a=sm[(op,'section')];b=sm[(op,'hand')];stable=float(a['mean_train_held_dot'])>0 and float(b['mean_train_held_dot'])>0 and float(a['direction_accuracy'])>=d['decision']['minimum_direction_accuracy'] and float(b['direction_accuracy'])>=d['decision']['minimum_direction_accuracy'] and min(float(a['max12_p']),float(b['max12_p']))<=d['decision']['max12_p_le'];classes[op]='DOMAIN_STABLE' if stable else 'DOMAIN_MIXED_OR_UNSTABLE'
 status='SELECTED_OPERATIONS_DOMAIN_STABLE' if all(v=='DOMAIN_STABLE' for v in classes.values()) else 'SELECTED_OPERATIONS_DOMAIN_MIXED';counter=[{'counterexample_id':'C01','finding':'The three operations were selected on the full GDT303 corpus before domain splitting.','impact':'This is post-selection stability, not independent confirmation.'},{'counterexample_id':'C02','finding':'Exact pair-domain cells overlap across section/register/Currier/hand views.','impact':'The twelve views are corrections over one dependent family, not twelve replications.'},{'counterexample_id':'C03','finding':'Only exact forms with support on both sides of a split are scorable.','impact':'Rare or domain-exclusive realizations remain outside the claim.'},{'counterexample_id':'C04','finding':'GDT289 already rejects a global cross-host wrapper-position rule.','impact':'Any stability is specific to these sparse exact one-field operations.'},{'counterexample_id':'C05','finding':'Physical FIRST/MIDDLE/LAST is a layout role, not syntax or semantics.','impact':'No linguistic function follows from a stable delta.'},{'counterexample_id':'C06','finding':'No f84 row occurs in the source.','impact':'The sealed holdout remains untouched.'}];write(PAIR,pairrows);write(CELL,cellrows);write(SCORES,scores);write(NULL,[{'world_index':w,'max12_standardized_dot':f'{maxz[w]:.12f}'} for w in range(d['null_worlds'])]);write(COUNTER,counter)
 report=['# GDT307 — selected renderer-operation domain stability','',f'Status: **{status}**.','', '> The operation family was selected on the complete GDT303 corpus. This is frozen post-selection domain stability, not independent discovery.','', '| operation | section dot/accuracy/max-p | hand dot/accuracy/max-p | register dot | Currier dot | class |','|---|---:|---:|---:|---:|---|']
 for op in d['operations']:
  a,b,c,e=(sm[(op,x)] for x in ('section','hand','register','currier'));report.append(f"| `{op}` | {float(a['mean_train_held_dot']):+.4f}/{float(a['direction_accuracy']):.3f}/{a['max12_p']} | {float(b['mean_train_held_dot']):+.4f}/{float(b['direction_accuracy']):.3f}/{b['max12_p']} | {float(c['mean_train_held_dot']):+.4f} | {float(e['mean_train_held_dot']):+.4f} | {classes[op]} |")
 report+=['','## Interpretation','', 'The selected exact operations are evaluated only where the same exact forms occur inside and outside a held domain. `ch->s` is strongly direction-stable in all four domain views. `d->s` is also direction-stable by the frozen rule, with its strongest corrected evidence in held hand/register and a weaker held-section correction. In contrast, `NONE->q` has small positive mean dots but fails section and hand direction accuracy. Thus `s` substitution is the more domain-stable physical-position operation, while q remains better characterized by its known post-DY host/register ecology. This cannot rescue the failed global wrapper model because the effect is confined to selected, exact compatible pairs.','','## Claim ceiling','',d['claim_ceiling']+' No f84 row was opened, parsed, retained, joined, or scored.'];REPORT.write_text('\n'.join(report)+'\n');outputs=[PAIR,CELL,SCORES,NULL,COUNTER,REPORT];inputs=[SOURCE,FROZEN,R/'gdt307_capacity.tsv',R/'gdt307_design_validation.json',R/'gdt303_result.json',R/'gdt289_result.json'];res={'schema':'GDT307_RENDERER_OPERATION_DOMAIN_STABILITY_RESULT_V1','status':status,'classifications':classes,'summary':{'pair_domain_cells':len(pairrows),'host_domain_cells':len(cellrows),'stable_operations':sum(v=='DOMAIN_STABLE' for v in classes.values())},'provenance':'POST_SELECTION_STABILITY_OF_GDT303_OPERATIONS','semantic_assignments':0,'claim_ceiling':d['claim_ceiling'],'f84':{'input_files':0,'opened':False,'parsed':False,'retained':False,'joined':False,'scored':False},'inputs':{p.name:sha(p) for p in inputs},'documents':{METHOD.name:sha(METHOD),REPORT.name:sha(REPORT)},'implementation':{Path(__file__).name:sha(Path(__file__))},'outputs':{p.name:sha(p) for p in outputs}};res['content_sha256']=can(res);RESULT.write_text(json.dumps(res,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':status,'classes':classes,'scores':scores},sort_keys=True))
if __name__=='__main__':main()
