#!/usr/bin/env python3
"""Independent integrity/aggregate validator for GDT123."""
import csv,hashlib,json,math
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parent;RESULT=ROOT/'gdt123_result.json';OUT=ROOT/'gdt123_validation.json';AXES=('RAYS_8_VS_7','TAIL_2_VS_1','COLOR_RED_VS_YEL')
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def csha(v):return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()
def rows(p):
 with Path(p).open(encoding='utf-8',newline='') as h:return list(csv.DictReader(h,delimiter='\t'))
def main():
 r=json.loads(RESULT.read_text());i=rows(ROOT/'gdt123_q20_page_host_codeword_inventory.tsv');a=rows(ROOT/'gdt123_q20_page_host_codeword_atlas.tsv');n=rows(ROOT/'gdt123_q20_page_host_codeword_null.tsv');x=rows(ROOT/'gdt123_q20_page_host_codeword_counterexamples.tsv');c={}
 c['schema']=r['schema']=='GDT123_Q20_PAGE_HOST_CODEWORD_ATLAS_RESULT_V1';c['inventory']=len(i)==281 and [int(z['feature_index']) for z in i]==list(range(281)) and len({(z['scope'],z['page_host']) for z in i})==281;c['support_gate']=all(int(z['zl_records'])>=5 and int(z['zl_folios'])>=2 for z in i);c['atlas']=len(a)==843 and len({(z['axis'],z['scope'],z['page_host']) for z in a})==843 and {z['axis'] for z in a}==set(AXES);c['selector']=all(abs(float(z['selector_cost_bits'])-math.log2(2*843))<1e-9 and abs(float(z['selector_paid_gain_bits'])-(float(z['gaussian_gain_bits'])-float(z['selector_cost_bits'])))<1e-9 for z in a);c['effect_fields']=all(abs(abs(float(z['effect_signed']))-float(z['effect_abs']))<1e-12 and len(z['leave_one_folio_effects'].split('|'))==7 for z in a);c['p_bounds']=all(0<float(z['local_p'])<=1 and 0<float(z['max_library_p'])<=1 for z in a);c['null']=len(n)==4096 and [int(z['world']) for z in n]==list(range(4096));labels=Counter(z['label'] for z in a);c['labels']=dict(labels)==r['label_counts'];top=min(a,key=lambda z:(float(z['max_library_p']),-float(z['effect_abs']),z['candidate_id']));c['top']=top['candidate_id']==r['top_candidate']['candidate_id'] and abs(float(top['effect_signed'])-r['top_candidate']['effect_signed'])<1e-10;c['interesting_empty']=not [z for z in a if z['label']=='INTERESTING_EXPLORATORY'] and r['interesting_candidates']==[];c['counter']=len(x)==69 and all(float(z['local_p'])<=.1 for z in x);c['status']=r['status']=='Q20_EXACT_PAGE_HOST_VISUAL_ATLAS_NO_GLOBAL_SURVIVOR';c['no_semantic_assignment']=all(z['claim_state']=='EXPLORATORY_EXACT_HOST_ASSOCIATION_NO_MEANING' for z in a);c['f84']=all(v is False for v in r['f84r'].values());c['input_hashes']=all(sha(ROOT/k)==v for k,v in r['inputs'].items());c['implementation_hashes']=all(sha(ROOT/k)==v for k,v in r['implementation'].items());c['output_hashes']=all(sha(ROOT/k)==v for k,v in r['outputs'].items());c['document_hashes']=all(sha(ROOT/k)==v for k,v in r['documents'].items());z=dict(r);claim=z.pop('result_content_sha256');c['content_hash']=claim==csha(z);status='PASS_INTEGRITY_LIBRARY_AND_POSTSELECTION_ACCOUNTING' if all(c.values()) else 'FAIL';out={'schema':'GDT123_Q20_PAGE_HOST_CODEWORD_ATLAS_VALIDATION_V1','status':status,'scope':'Independent library/atlas/null/count/selector/label/hash validation; nuisance residuals and permutation correlations are not independently rerun.','checks_total':len(c),'checks_passed':sum(c.values()),'checks':c,'result_sha256':sha(RESULT),'validator_sha256':sha(Path(__file__))};OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':status,'passed':sum(c.values()),'total':len(c)},sort_keys=True))
if __name__=='__main__':main()
