"""Exact length consequence of the frozen965writer; not a native parser."""
from pathlib import Path
import hashlib,json
B=Path('research_registry/proposals/production_origin_supply_20261003')
raw=B/'HUMAN_MEASURED_MATERIAL_LIST_RAW_20261006.json'
source=Path('experiments/yolo/gdt1200_stable_part_repetition_capacity/REPORT.md')
units=json.loads(raw.read_text())['design']['working_units']
# Arrays explicitly use the contract's working units, including atomic ch.
bases=[['d','a','l'],['a','l'],['ch'],['o','l']]
rows=[]
for base in bases:
    family=[base,base+['y'],base+['d','y']]
    assert all(u in units for f in family for u in f)
    lengths=[len(f) for f in family]
    residues=[n%3 for n in lengths]
    assert len(set(residues))==3
    rows.append({'base':''.join(base),'forms':[''.join(f) for f in family],'working_unit_lengths':lengths,'residues_mod3':residues,'minimum_distinct_fixed_bases':3})
r={
 'status':'ONE_FIXED_BASE_PREPARATION_ACCOUNT_EXCLUDED_CONDITIONALLY',
 'idea':'IDEA000965',
 'scope':'Analytic consequence applied to four already reported formal families. No new native count, unit discovery, statistical selection or meaning.',
 'contract':str(raw),'contract_sha256':hashlib.sha256(raw.read_bytes()).hexdigest(),
 'family_primary':str(source),'family_primary_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
 'proof':'For a fixed ordinary material root R and any preparation history H, length(write(R,H))=length(R)+3*length(H). Thus every pair in that one-base family has length difference divisible by3. An identical statement holds for one fixed literal-name frame. Bijective renaming of atomic working units preserves lengths. B,By,Bdy instead have lengths n,n+1,n+2, so every pair differs by1or2. They require at least3fixed base spellings if all are complete material words in this writer.',
 'families':rows,
 'source_scope':'1200reports these exact whole-form triplets in each of ZL,IT,RF separately. They are alternative transcriptions. No new assertion that the strings share a native morpheme or lexical referent.',
 'assumptions':['Each tested written form is a complete logical material word, not a physical fragment or a control.','The fixed22working-unit representation is used, including atomic ch.','All compared forms proposed as one material family would use the same canonical root or same canonical literal name.','Only the unchanged ordered rro/rre preparation suffixes generate its productive variants.','No contraction, erasure, multi-unit recoding, optional aliases, changed name/root policy or different derivation is inserted.'],
 'retained_positives':['The artificial965lesson remains readable and open to new literal names.','Separate root entries can store all four triplets; the architecture is not globally ruled out.','The prior complete-message control cost proof and1175specific spelling-cost failure stay unchanged.'],
 'decision':'Do not claim that965explains1200short-extension families through its preparation morphology. Their coexistence can be accommodated lexically, at extra lexical cost, but is not generated by the advertised common-root rule. No repair or larger generator selected.',
 'limits':['No native dry/ground/material meaning assigned.','This is not a general ban on agglutination or short suffixes.','The data do not independently establish that the formal triplets must be one semantic family.','No inference from a quoted stock name to a new concept definition.'],
 'validation':'Universal algebra above; four finite length calculations checked against n,n+1,n+2. This is not independent semantic evidence.'
}
(B/'MATERIAL965_LENGTH_OBLIGATION_RESULT_20261007.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'status':r['status'],'families':rows},ensure_ascii=False))
